spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ruckus_exam?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    separator: //

  redis:
    host: 127.0.0.1
    port: 6379
    #password: 123456
    pool:
      max-active: 100
      max-idle: 10
      max-wait: 1000000
    timeout: 5000

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true